[package]
name = "advent-of-code-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = { version = "0.1.41", features = ["log"] }
tracing-subscriber = "0.3.19"


[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
