[project]
name = "advent-of-code-2024"
version = "1.0.0"
description = "Advent of Code 2024"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "mypy==1.13.0",
    "ruff==0.8.2"
]


[tool.mypy]
strict = true
mypy_path = "$MYPY_CONFIG_FILE_DIR/"
files = "src/**/*.py"
